---
- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Display the config
      debug:
        msg: "Hello darkness my old friend"
